# Generated by Django 2.1.7 on 2019-03-12 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Undisclosed', max_length=200, null=True)),
                ('companyType', models.CharField(default='Undisclosed', max_length=200, null=True)),
                ('employeeCountRange', models.CharField(default='Undisclosed', max_length=200, null=True)),
                ('foundedYear', models.CharField(default='Undisclosed', max_length=200, null=True)),
                ('industries', models.TextField(default='Undisclosed', max_length=500, null=True)),
                ('numFollowers', models.CharField(default='Undisclosed', max_length=200, null=True)),
                ('specialties', models.TextField(default='Undisclosed', max_length=1000, null=True)),
                ('squareLogoUrl', models.CharField(default='Undisclosed', max_length=500, null=True)),
                ('websiteUrl', models.CharField(default='Undisclosed', max_length=500, null=True)),
                ('group', models.CharField(default='Undisclosed', max_length=200, null=True)),
            ],
        ),
    ]
