# Generated by Django 2.2 on 2020-10-27 16:35

import core.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Undisclosed', max_length=200, null=True)),
                ('companyType', models.CharField(default='Undisclosed', max_length=200, null=True)),
                ('employeeCountRange', models.CharField(default='Undisclosed', max_length=200, null=True)),
                ('foundedYear', models.CharField(default='Undisclosed', max_length=200, null=True)),
                ('industries', models.TextField(default='Undisclosed', max_length=500, null=True)),
                ('numFollowers', models.CharField(default='Undisclosed', max_length=200, null=True)),
                ('specialities', models.TextField(default='Undisclosed', max_length=1000, null=True)),
                ('squareLogoUrl', models.CharField(default='Undisclosed', max_length=500, null=True)),
                ('websiteUrl', models.CharField(default='Undisclosed', max_length=500, null=True)),
                ('group', models.CharField(default='Undisclosed', max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='MyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, default='guest', max_length=254)),
                ('image', models.ImageField(default='portraits/default.jpg', upload_to=core.utils.content_file_name)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
